### PR TITLE
Remove docker ecr recipe from worker compiliation. Replace with clortho based credentials creation

### PR DESCRIPTION
**Pull request by JoeNunnelley**
### Description
unable to use the socrata-docker::ecr configuration recipe in a packer based scenario (like other credential initialization operations). Therefore, need to convert to doing ecr tooling initialization off of clortho encrypted s3 bucket.

### Check List

- [ ] New functionality includes tests
- [x ] All tests pass
- [ ] CHANGELOG has been updated
- [x ] Version has been bumped in metadata
- [x] Commits have been squashed, as appropriate
- [x ] Commits include descriptive messages, subjects written in the imperative

### CODE REVIEW

**Comment by znep** [comment]
Why do the workers need creds from clorth, can't they get access from the IAM role like, for example, the mesos slaves?

**Comment by JoeNunnelley** [comment]
@znep the creds from clortho are laid down at boot time for the worker because we don't want to store them on the compiled AMI, the nodes are not registered with chef or managed by chef so we don't have access to the chef databags. Therefore I used the clortho system.

**Comment by znep** [comment]
@JoeNunnelley Again, why can't they get access via an IAM role like the workers do?  They shouldn't need hardcoded creds from clorth or chef or anywhere else.

**Comment by JoeNunnelley** [comment]
I pull credentials for the various tool chain config files from clortho that I then use ERB to transform and lay down on the worker file system at boot time (like .gemrc, .bundle/config, .sbt/*, etc).  can you do that with an IAM role? I didn't think you could.  Also, this is not a new mechanism, we've been using it for some time.  I AM relying on the IAM role for ECR access and have removed that bit of code I added earlier.

**Comment by znep** [comment]
@JoeNunnelley ok, yes, thats fine.  I was just talking about the changes in this PR for ECR.

**Pull request merged**
