### PR TITLE
shifting supported ruby to newer set (2.3.5, 2.3.6, 2.5.0) with 2.3.6…

### PR DESCRIPTION
**Pull request by JoeNunnelley**
… default

### CODE REVIEW

**Comment by JoeNunnelley** [comment]
@smooshy I kitchen converge these locally and verify the config is as expected.

**Comment by smooshy** [comment]
oic. i thought there were unit tests like there are for other cookbooks.

**Comment by JoeNunnelley** [comment]
added a couple of tests for you @smooshy  :)

**Comment by smooshy** [comment]
Thanks for adding tests. They seem to fail, though. ;)

**Pull request merged**
