### PR TITLE
updates from last build of official amis

### PR DESCRIPTION
**Pull request by JoeNunnelley**
- commenting out unecessary kitchen test permutations. leaving them in though for local debugging purposes.
- updating readme with currently used AMI ids

### CODE REVIEW

**Comment by JoeNunnelley** [comment]
retest please

**Comment by JoeNunnelley** [comment]
retest this please

**Comment by courtneyspurgeon** [comment]
:shipit:

**Comment by JoeNunnelley** [comment]
thanks.

**Pull request merged**
