### PR TITLE
EN-18087: Update to ruby_rbenv 2.0

### PR DESCRIPTION
**Pull request by saraid**

### CODE REVIEW

**Comment by JoeNunnelley** [comment]
looking at why this is failing

**Comment by JoeNunnelley** [comment]
looks like builds of the ruby_rbenv cookbook are failing currently on supermarket. I can't seem to reference any of the recipes (system_install, default, global).

**Comment by JoeNunnelley** [comment]
updated this so it should work now. tested with converge.

**Comment by JoeNunnelley** [comment]
retest this please

**Comment by JoeNunnelley** [comment]
retest this please

**Comment by saraid** [comment]
This looks fine to me.

**Comment by JoeNunnelley** [comment]
:shipit:

**Pull request merged**
