### PR TITLE
Add SBT to the pg94 recipe

### PR DESCRIPTION
**Pull request by rjmac**
..because now the elixir stuff needs it

### CODE REVIEW

**Comment by vilterp** [comment]
linking to https://github.com/socrata/dsmapi/pull/20

**Comment by michaelb990** [comment]
🎉

**Comment by rjmac** [comment]
retest this please

**Comment by rjmac** [comment]
ok, it builds now, and has an sbt executable and installs java 8.  @michaelb990 still good?

**Comment by vilterp** [comment]
Still looks 👍 to me

**Pull request merged**
